In [4]:
import numpy as np
l=[1,2,3,4,5,6]
a=np.array(l)
a

array([1, 2, 3, 4, 5, 6])

In [9]:
# List to Array: Create a 1D NumPy array from the Python list [10, 20, 30, 40].
import numpy as np

l=[10,20,30,40]
print(np.array(l))
print(type(np.array(l)))
# Matrix from List of Lists: Create a 2D array (matrix) from [[1, 2], [3, 4]].
l=[[1,2],[3,4]]
print(np.array(l))
# Specify Data Type: Create an array of integers [1, 2, 3] but specify the data type as float32.
a=[1,2,3]
l=np.array(a,dtype='float')
l
# arange Basic: Create an array containing numbers from 0 to 9.
l=np.arange(10)
l
# arange with Start/Step: Create an array of all even numbers from 10 to 30.
l=np.arange(10,31,2)
l
# arange with Floats: Create an array from 0.0 to 1.0 with a step of 0.1.
a=np.arange(0,1,.1)
a
# linspace for Precision: Create an array of 11 equally spaced points between 0 and 5.
a=np.linspace(0,5,12)
a
# linspace Excluding Endpoint: Create an array of 10 equally spaced points between 0 and 10, not including 10.
a=np.linspace(0,10,10)
a
# zeros Array: Create a 1D array of 8 zeros.
z=np.zeros(8)
z
# zeros Matrix: Create a 4x4 matrix filled with zeros.
z=np.zeros((4,4))
z
# ones Matrix: Create a 3x5 matrix filled with ones.
print(np.ones((3,5)))
# empty Array: Create a 2x2 uninitialized array. Print it to see the "garbage" values.
print(np.empty((2,2)))
# full Array: Create a 5x5 matrix where every element is the number 7.
print(np.full((5,5),7))
# _like Functions: Create an array A. Then, create a new array B with the same shape as A but filled with zeros, using np.zeros_like().
a=np.array([1,2,3])
b=np.zeros_like(a)
b
# Identity Matrix: Create a 5x5 identity matrix.
n=np.identity(5)
print(n)
# Diagonal Matrix: Create a square matrix where the diagonal elements are [1, 5, 9, 14].
l=np.diag([1,5,9,14])
print(l)
# Random Floats: Create a 3x3 matrix with random float values between 0 and 1.
l=np.random.rand(3,3)
print(l)
# Random Integers: Create a 1D array of 10 random integers between 50 and 100.
l=np.random.randint(50,101,10)
print(l)
# Random Normal Distribution: Create a 4x4 matrix of random numbers from a standard normal distribution (mean=0, variance=1).
# Reproducible Randomness: Create a 3x3 matrix of random integers from 1 to 10, but make sure the result is the same every time the script is run. (Hint: np.random.seed())
# fromfunction: Create a 5x5 matrix where the element at (i, j) is i + j.
f=np.fromfunction(lambda i,j:i+j,(5,5))
print(f)
# Jagged Array Issue: Try to create an array from [[1, 2], [3, 4, 5]] and print its dtype to observe the object type.
a=np.array([1, 2, 3])
print(a)
print(type(a))
# Array from String: Convert the list of strings ['1', '2.5', '3.14'] into a float array.
# Copying an Array: Create an array A and a new array B that is a copy of A. Change an element in A and show that B is not affected.
# Read-Only Array: Create an array and make it read-only. Try to modify an element and observe the ValueError.
# Category B: Array Attributes and Inspection (26-40)
# Shape, Size, Ndim: Create a 3x4 matrix and print its shape, total number of elements, and number of dimensions.
a=np.zeros((3,4))
print(np.shape(a),len(a),a.ndim)
# Data Type: Create an array of floats and print its dtype.
a=np.array([1,2,3])
print(a.dtype)
# Item Size: Create an array of int64 and print the memory size (in bytes) of one element.
a=np.array([1,2,3],dtype='float')
print(a.itemsize)
# Total Bytes: Create a 4x5 array of float32 and calculate its total memory consumption in bytes.
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(a.nbytes)
# Transpose: Create a 2x3 matrix and print its transpose.
a=[[2,3,4],[5,6,7]]
b=np.array(a)
print(b.T)
# Check Contiguity (C-order): Create a standard C-order array and verify its C_CONTIGUOUS flag is True.

# Check Contiguity (F-order): Create a Fortran-order array and verify its F_CONTIGUOUS flag is True.
# Non-Contiguous Array: Create a non-contiguous array by taking a slice with a step (e.g., A[:, ::2]) and check its contiguity flags.
# Strides: Create a 3x4 array of int32 (4 bytes) and print its strides to understand how memory is traversed.
# Base Object: Create a view B from an array A (B = A[0:5]). Print B.base to show it refers back to A.
# Data Pointer: Print the data attribute of an array to see the memory buffer object.
# Array Report: Write a function that takes an array and prints a full report: its data, shape, strides, dtype, and total memory usage.
# Flatten vs Ravel (View): Create a C-contiguous array, ravel it, and show that modifying the raveled array changes the original.
# Flatten vs Ravel (Copy): Create a C-contiguous array, flatten it, and show that modifying the flattened array does not change the original.
# Check for NaN: Create an array with a np.nan value and use np.isnan() to get a boolean mask.
# Category C: Basic Indexing and Slicing (41-75)
# First and Last Element: Get the first and last element of a 1D array.
l=np.array([1,2,3,4,5])
print(l[0],l[-1])
# First and Last Row: Get the first and last row of a 2D array.
l=np.array([[1,2,3],[4,5,6]])
print(l[0],l[-1])
# First and Last Column: Get the first and last column of a 2D array.

# Slicing a 1D Array: From an array [0, 1, ..., 19], get the elements from index 5 to 15.
l=np.arange(20)
print(l[5:16])
# Slicing with a Step: From the same array, get every third element.
l[::3]
# Reverse an Array: Reverse a 1D array using slicing.
l[::-1]
# Accessing 2D Element: Get the element at row 2, column 3 of a 5x5 matrix.
l=np.arange(25,size=(5,5))
print(l[2,3])
# Get a Row: Get the entire second row of a 4x4 matrix.

# Get a Column: Get the entire third column of a 5x5 matrix.
# 2D Sub-matrix: Get the top-right 2x2 sub-matrix from a 4x4 matrix.
# Slice and Assign: Select the first row of a 3x3 matrix and set all its elements to 99.
# View vs Copy (Slicing): Create a slice of an array. Modify the slice and show that the original array is also modified.
# Boolean Indexing (Simple): From an array of integers, select all numbers greater than 50.
# Boolean Indexing (Complex): Select all numbers that are even and greater than 10.
# Boolean Assignment: In a random integer array, replace all odd numbers with -1.
# Fancy Indexing (1D): From an array A, select the elements at indices 1, 5, and 8.
# Fancy Indexing (2D Rows): From a 10x10 matrix, select rows 0, 3, and 7.
# Fancy Indexing (Specific Elements): From a 5x5 matrix, select the elements at coordinates (0,1), (2,3), and (4,0).
# Fancy Indexing for Assignment: In a 5x5 matrix, set the elements at (1,1) and (3,3) to 0.
# View vs Copy (Fancy Indexing): Use fancy indexing to get a sub-array. Modify it and show the original is not affected.
# take function: Use np.take() to select elements from a 1D array at specified indices.
# put function: Use np.put() to modify elements in a 1D array at specified indices.
# Diagonal Elements: Get the main diagonal elements of a 4x4 matrix.
# Off-Diagonal Elements: Get the diagonal elements one position above the main diagonal (k=1).
# Slicing 3D Array (Plane): Create a 3x3x3 array and select the entire second plane (axis 0, index 1).
# Slicing 3D Array (Column): From the same 3D array, select the center "column" (all of axis 0, row 1, col 1).
# Ellipsis Slicing: From a 4x3x2 array, select all elements where the last dimension's index is 0 (i.e., arr[..., 0]).
# np.ix_ for Sub-Grids: From a 10x10 matrix, create a sub-grid using rows [1, 3, 5] and columns [2, 4, 6].
# where for Indices: Find the indices of all elements greater than 10 in a 1D array.
# Replace with where: Use np.where() to replace all negative numbers in an array with 0, and leave positive numbers as they are.
# nonzero: Find the indices of all non-zero elements in an array containing many zeros.
# Border Elements: Create a 10x10 matrix of ones and set the border elements to 0.
# Checkerboard Pattern: Create an 8x8 matrix with a checkerboard pattern of 0s and 1s using slicing.
# Extract with extract: Use np.extract() with a condition to get elements from an array.
# Conditional Slice Assignment: From a 2D array, select all rows where the first element is greater than 5.
# Clip Values: Create an array of random numbers and clip all values to be within the range [0.2, 0.8].
# Index of Max Value: Find the index of the maximum value in a 1D array.
# Part 2: Core Operations (Programs 76-200)
# Category D: Mathematical & Statistical Operations (76-130)
# Scalar Addition: Add the number 100 to every element in an array.
# Element-wise Addition: Add two 1D arrays of the same size.
# Element-wise Multiplication: Multiply two 2x3 matrices element-wise.
# Broadcasting (Vector to Matrix): Add a 1D array of size 3 to each row of a 4x3 matrix.
# Broadcasting (Column Vector): Add a column vector (shape (4,1)) to each column of a 4x3 matrix.
# Matrix Multiplication (@): Multiply a 3x4 matrix by a 4x2 matrix.
# Dot Product: Calculate the dot product of two 1D vectors.
# Universal Functions (Ufuncs): Calculate the sine, cosine, and natural logarithm of every element in an array.
# Sum of All Elements: Find the sum of all elements in a 2D array.
# Sum Along Axis (Columns): Find the sum of each column in a 2D array.
# Sum Along Axis (Rows): Find the sum of each row in a 2D array.
# Mean, Median, Std Dev: Calculate the mean, median, and standard deviation of a 1D array.
# Min/Max: Find the minimum and maximum values in a 2D array.
# Percentiles: Find the 25th and 75th percentiles of a large random array.
# Cumulative Sum: Calculate the cumulative sum of a 1D array.
# Cumulative Product: Calculate the cumulative product of a 1D array.
# Z-score Normalization: Normalize a 1D array by subtracting the mean and dividing by the standard deviation.
# Min-Max Scaling: Scale a 1D array to the range [0, 1].
# Matrix Determinant: Calculate the determinant of a 3x3 matrix.
# Matrix Inverse: Find the inverse of a 2x2 matrix.
# Solve Linear Equations: Solve the system of linear equations 3x + y = 9 and x + 2y = 8.
# Eigenvalues and Eigenvectors: Find the eigenvalues and eigenvectors of a square matrix.
# Singular Value Decomposition (SVD): Decompose a matrix using SVD.
# Correlation Coefficient: Compute the correlation coefficient matrix for a 2D array where rows represent variables.
# Covariance Matrix: Compute the covariance matrix for the same array.
# Rounding: Round all elements of a float array to 2 decimal places.
# Floor and Ceil: Apply floor and ceil to a float array.
# Complex Numbers: Create an array of complex numbers and calculate their absolute values.
# Exponentiation: Calculate e^x for every element x in an array.
# Handling Division by Zero: Divide one array by another, but use np.divide with a where clause to avoid errors when the denominator is zero.
# Outer Product: Compute the outer product of two 1D vectors.
# Cross Product: Compute the cross product of two 3-element vectors.
# Euclidean Distance: Calculate the Euclidean distance between two points (represented as 1D arrays).
# Sum of Squares: Find the sum of the squared elements of an array.
# Custom Ufunc (vectorize): Write a Python function that returns 'big' if a number is > 10 and 'small' otherwise. Use np.vectorize to apply it to an array.
# all and any: Check if any element in an array is greater than 10, and if all elements are positive.
# isclose for Floats: Show that 0.1 + 0.2 == 0.3 is False, but np.isclose(0.1 + 0.2, 0.3) is True.
# Array Equality: Use np.array_equal to check if two arrays have the same shape and elements.
# Bitwise Operators: Create two integer arrays and apply bitwise AND (&) and OR (|) operations.
# Logical Operators: Create two boolean arrays and apply np.logical_xor.
# keepdims Argument: Calculate the sum of each row in a 2D array, but keep the result's dimensions as (n_rows, 1) using keepdims=True.
# ufunc.at: Create an array of zeros and add values to specific indices, including repeated indices, using np.add.at to see correct accumulation.
# bincount: Create a histogram of an array of integers using np.bincount.
# digitize: Create a set of bins and use np.digitize to find which bin each element of an array belongs to.
# clip: Force all elements in an array to be within a specific range [min, max].
# Matrix Trace: Calculate the trace (sum of diagonal elements) of a matrix.
# Frobenius Norm: Calculate the Frobenius norm of a matrix using np.linalg.norm.
# Polynomial Evaluation: Create a polynomial p(x) = 3x^2 + 2x + 1 and evaluate it at x=5 using np.polyval.
# Polynomial Fitting: Fit a 2nd-degree polynomial to a set of noisy data points using np.polyfit.
# Vandermonde Matrix: Create a Vandermonde matrix from a 1D array.
# Kronecker Product: Compute the Kronecker product of two small matrices.
# einsum for Sum: Use np.einsum to compute the sum of all elements in an array.
# einsum for Transpose: Use np.einsum to transpose a matrix.
# einsum for Dot Product: Use np.einsum to compute the dot product of two vectors.
# einsum for Matrix Multiplication: Use np.einsum to perform matrix multiplication.
# Category E: Array Manipulation (131-160)
# Reshaping: Convert a 1D array of 12 elements into a 3x4 matrix.
# Flattening: Convert a 3x4 matrix into a 1D array.
# Concatenate (Rows): Join two 2x3 matrices along the row axis (axis=0).
# Concatenate (Columns): Join two 3x2 matrices along the column axis (axis=1).
# vstack: Vertically stack two 1D arrays.
# hstack: Horizontally stack two 1D arrays.
# dstack: Depth-stack two 2x2 arrays.
# Splitting (Vertical): Split a 6x4 matrix into 3 equal 2x4 sub-arrays vertically.
# Splitting (Horizontal): Split a 6x4 matrix into 2 equal 6x2 sub-arrays horizontally.
# hsplit and vsplit: Use the convenience functions hsplit and vsplit.
# Adding a Dimension: Convert a 1D array of shape (5,) to a column vector of shape (5, 1) using np.newaxis.
# Squeezing: Remove single-dimensional entries from the shape of an array.
# repeat: Repeat each element of a 1D array 3 times.
# tile: Tile a 1D array [1, 2] to create [1, 2, 1, 2, 1, 2].
# insert: Insert the value 99 at index 3 in a 1D array.
# delete: Delete the element at index 4 from a 1D array.
# append Warning: Use np.append in a loop to add 1000 numbers to an array. Time this operation to see the performance cost. (This is a "what not to do" exercise).
# append Correct Usage: The better way: Pre-allocate an array and fill it in a loop. Time this and compare.
# Flipping (Up/Down): Flip a 2D array vertically.
# Flipping (Left/Right): Flip a 2D array horizontally.
# roll: Roll the elements of a 1D array by 3 positions.
# pad: Pad a 3x3 array with a border of 0s on all sides.
# pad (Edge): Pad an array using the edge mode to replicate border values.
# Unique Elements: Find the unique elements in an array with duplicates.
# Unique with Counts: Find the unique elements and their counts.
# Set Intersection: Find the common elements between two arrays.
# Set Difference: Find the elements in one array that are not in another.
# Union of Sets: Find the union of elements from two arrays.
# in1d: Check which elements of a first array are present in a second array, returning a boolean array.
# Swap Rows: In a 2D array, swap row 1 with row 3.
# Category F: Sorting and Searching (161-175)
# Sort 1D Array: Sort a 1D array of random integers.
# In-place Sort: Sort a 1D array in-place using its sort() method.
# argsort: Get the indices that would sort an array.
# Sort by Column: Sort a 2D array based on the values in its second column.
# Sort Along Axis: Sort each row of a 2D array independently.
# searchsorted: Find the indices where elements should be inserted into a sorted array to maintain order.
# argmax and argmin: Find the index of the maximum and minimum value in each column of a 2D array.
# Lexicographical Sort: Perform a lexicographical sort on a structured array (see next section).
# Partitioning: Use np.partition to find the 5 smallest values in an array without fully sorting it.
# nan-aware Sorts: Create an array with nan values and use np.nansort.
# nanargmax: Find the index of the maximum value in an array with nans, ignoring them.
# Maximum of two arrays: Create a new array that contains the element-wise maximum of two other arrays.
# Searching for a value: Check if a specific value exists in an array.
# Finding first occurrence: Find the index of the first occurrence of a value greater than a threshold.
# Finding duplicates: Find all duplicate entries in an array.
# Category G: I/O and Structured Arrays (176-200)
# Save to .npy: Save a NumPy array to a binary file data.npy.
# Load from .npy: Load the array back from data.npy.
# Save to .npz: Save two different arrays (A and B) into a single compressed file data.npz.
# Load from .npz: Load the data.npz file and access array B.
# Save to Text: Save a 2D array to a text file matrix.txt with comma delimiters.
# Load from Text: Load the data from matrix.txt.
# savetxt with Formatting: Save a float array to a text file, formatting each number to have 3 decimal places.
# genfromtxt for Missing Data: Create a text file with missing values (e.g., empty fields). Load it using np.genfromtxt, replacing missing values with -99.
# genfromtxt with Headers: Load a CSV file but skip the header row.
# Memory-Mapped Array: Create a large array on disk using np.memmap and manipulate a slice of it.
# Define Structured Dtype: Define a data type for an employee record: name (string), age (int), salary (float).
# Create Structured Array: Create a structured array for 3 employees using the dtype from the previous step.
# Access by Field: From the structured array, select all the employee names.
# Calculate on Field: Calculate the average salary from the structured array.
# Filter Structured Array: Select all employees who are older than 30.
# Sort Structured Array: Sort the employee array by salary in descending order.
# Nested Dtypes: Create a structured array where one field is itself a 2x2 matrix.
# Record Array: Create a record array and access a field using attribute notation (e.g., rec.salary).
# From String to Datetime: Use np.datetime64 to create an array of dates from strings.
# Date Arithmetic: Create two date arrays and find the time difference between them.
# Business Day Calendar: Create a range of dates and count the number of business days.
# Save complex numbers: Save an array with complex numbers to a text file and load it back.
# Load specific columns: Load only the 1st and 3rd columns from a text file.
# Save to CSV with header: Save a numpy array to a csv and write a custom header.
# View array with different dtype: Create an int32 array and view its memory as int8 to see the underlying bytes.
# Part 3: Advanced and Applied NumPy (Programs 201-300)
# Category H: Advanced Techniques (201-250)
# as_strided for Moving Average: Use this "dangerous" function to create a view of all overlapping windows of an array, then calculate a moving average without loops.
# FFT (Fast Fourier Transform): Create a signal with two frequencies. Compute its FFT and plot the spectrum to identify the frequencies.
# Inverse FFT: Transform the frequency domain data from the previous step back to the time domain.
# Convolution for Blurring: Create a simple 2D kernel (e.g., a 3x3 box blur) and convolve it with a 2D array (image) to blur it.
# Random Walk: Simulate a 1D random walk of 1000 steps.
# 2D Random Walk: Simulate a 2D random walk.
# Monte Carlo Pi Estimation: Use random sampling within a square to estimate the value of Pi.
# Game of Life (Simulation): Implement Conway's Game of Life on a 2D grid using array shifting and boolean logic.
# Mandelbrot Set: Generate and visualize the Mandelbrot set using complex numbers and broadcasting.
# Gradient Descent: Implement a simple gradient descent algorithm to find the minimum of the function f(x) = x^2 + 3x + 5.
# Batch Matrix Multiplication (einsum): Given two 3D arrays of shape (10, 3, 4) and (10, 4, 5), perform batch matrix multiplication to get a result of shape (10, 3, 5).
# Outer Product (einsum): Compute the outer product using einsum.
# Performance Profiling (timeit): Compare the speed of np.dot vs. a Python for loop for vector dot product.
# In-place vs. Standard Operations: Compare the memory usage of A = A + B vs. A += B.
# Conditional Selection with np.select: Create a list of conditions and a corresponding list of choices to create a new array.
# Prime Number Sieve: Implement the Sieve of Eratosthenes to find all prime numbers up to N using a boolean array.
# One-Hot Encoding: Convert a 1D array of integer labels into a one-hot encoded 2D matrix.
# Softmax Function: Implement the softmax function, a common activation in neural networks.
# Run-Length Encoding: Implement a basic run-length encoding (e.g., [1,1,1,2,2,3] -> [3,1,2,2,1,3]).
# Block Matrix Creation: Create a 4x4 block matrix from four 2x2 matrices.
# Interleaving Arrays: Interleave two 1D arrays [1,3,5] and [2,4,6] to get [1,2,3,4,5,6].
# Find Nearest Value: For each element in an array A, find the closest value in another array B.
# Replace NaN with Mean: Replace all NaN values in an array with the mean of the non-NaN elements.
# Gaussian Kernel: Create a 2D Gaussian kernel.
# Distance Matrix: Given a set of 2D points, compute the pairwise distance matrix.
# Row-wise subtraction of mean: From each row of a matrix, subtract the mean of that row.
# Finding local maxima: Find all the local maxima (peaks) in a 1D array.
# Weighted Average: Calculate the weighted average of an array.
# Jacobi Iteration: Implement the Jacobi method for solving a system of linear equations.
# PageRank Algorithm (Simple): Implement a simplified version of the PageRank algorithm on a small transition matrix.
# Image Quantization: Reduce the number of colors in an image using np.digitize.
# Sobel Edge Detection: Apply a Sobel filter to a 2D array to detect horizontal and vertical edges.
# Histogram of Oriented Gradients (HOG) - Step 1: Calculate the gradient magnitude and orientation for each pixel in a 2D array.
# Array to Bytes and Back: Convert a NumPy array to a byte string and then reconstruct the array from the bytes.
# Find Runs of True: In a boolean array, find the start and end indices of consecutive runs of True.
# Cartesian Product: Compute the Cartesian product of two 1D arrays.
# Shuffling Rows: Shuffle the rows of a 2D matrix.
# Bézier Curve: Generate points for a quadratic Bézier curve.
# Create a Lagged Array: Create a time-series array and generate a new array with lagged versions of the original.
# Autocorrelation: Calculate the autocorrelation of a 1D signal.
# Creating a Hankel matrix: Create a Hankel matrix from a given vector.
# Rolling window statistics: Calculate the rolling standard deviation on a 1D array without a loop.
# Find the most frequent value: Find the most frequent value in an array.
# Group by value: Group a 2D array by the values in one of its columns.
# Gaussian Elimination: Implement forward elimination step of Gaussian elimination.
# Linear Interpolation: Implement a simple 1D linear interpolation.
# Log-sum-exp trick: Implement the log-sum-exp function for numerical stability.
# QR Decomposition: Perform QR decomposition on a matrix.
# Check for Palindrome: Check if an array is a palindrome.
# Computing Moving Correlation: Compute the moving correlation between two time-series arrays.
# Category I: Integration with Other Libraries (251-275)
# (These may require pip install matplotlib pandas pillow scikit-learn scipy)
# Matplotlib: Basic Plot: Plot a sine wave using a NumPy array for the x and y coordinates.
# Matplotlib: Histogram: Create a histogram of 1000 random numbers drawn from a normal distribution.
# Matplotlib: Scatter Plot: Create a scatter plot from two 1D NumPy arrays.
# Matplotlib: Image Display: Create a random 50x50 array and display it as an image using imshow.
# Pandas: to DataFrame: Create a Pandas DataFrame from a 2D NumPy array with custom column names.
# Pandas: from DataFrame: Convert a Pandas DataFrame column back into a NumPy array using .to_numpy().
# Pandas: Mixed Dtypes: Create a DataFrame with mixed data types and observe the dtype of the resulting NumPy array after conversion.
# Pillow: Load Image: Load an image file into a NumPy array.
# Pillow: Manipulate Image: Convert the loaded image array to grayscale by averaging the RGB channels.
# Pillow: Save Image: Save the modified grayscale NumPy array back to an image file.
# 2s61. SciPy: Filtering: Use scipy.ndimage.gaussian_filter to blur an image represented by a NumPy array.
# SciPy: Interpolation: Use scipy.interpolate to interpolate missing values in a NumPy array.
# SciPy: Optimization: Use scipy.optimize.minimize with a function that operates on NumPy arrays.
# SciPy: Statistics: Use scipy.stats.ttest_ind to perform a t-test on two NumPy arrays.
# Scikit-learn: Create Dataset: Create a simple dataset for a machine learning model using NumPy arrays for features X and target y.
# Scikit-learn: Fit a Model: Use the NumPy arrays to fit a simple LinearRegression model from scikit-learn.
# Scikit-learn: Preprocessing: Use sklearn.preprocessing.StandardScaler on a NumPy feature matrix.
# Numba: JIT Compilation: Write a slow Python function with a loop that processes a NumPy array. Use @numba.jit to speed it up and time the difference.
# Cython: Interfacing: Write a simple Cython function that takes a NumPy array and processes it, showing how to declare types for speed.
# Audio Processing (SciPy): Generate a NumPy array representing a tone and save it as a .wav file using scipy.io.wavfile.
# Masked Arrays: Create a masked array where some data is invalid.
# Masked Array Calculation: Compute the mean of the masked array, showing that the masked values are ignored.
# Dask: Parallel NumPy: Create a large Dask array and perform a simple computation (like .mean().compute()) to see how it works with chunked NumPy arrays.
# H5Py: Storing Large Arrays: Store a very large NumPy array in an HDF5 file.
# Pygame Integration: Create a NumPy array representing a screen surface and update a Pygame display from it.
# Category J: Puzzles & Challenges (276-300)
# Magic Square: Write a function to check if a 2D array is a magic square (all rows, columns, and diagonals sum to the same value).
# Sudoku Validator: Write a function that takes a 9x9 NumPy array and checks if it's a valid Sudoku solution.
# Connect Four Win Condition: Given a 6x7 grid (NumPy array), check if a player has won Connect Four.
# Minesweeper Field: Given a boolean array representing mine locations, create the Minesweeper field with the numbers of adjacent mines.
# Image Tiling: Take a large image (NumPy array) and break it into a grid of smaller, non-overlapping tiles.
# Water Retention: Given a 1D array representing a height map, calculate how much water it would retain after rain.
# Shortest Path on a Grid: Find the shortest path from a start to an end point on a grid with obstacles, using Breadth-First Search on a NumPy array.
# Perlin Noise: Generate 2D Perlin noise.
# Matrix Power: Compute the N-th power of a matrix efficiently using eigenvalue decomposition.
# Strassen's Algorithm: Implement Strassen's algorithm for faster matrix multiplication (a theoretical exercise).
# Levenshtein Distance: Calculate the Levenshtein (edit) distance between two integer sequences using a dynamic programming table (a 2D NumPy array).
# Curve Fitting with RANSAC: Implement the RANSAC algorithm to robustly fit a line to data with many outliers.
# Kalman Filter (Simple 1D): Implement a simple 1D Kalman filter to track a moving object with noisy sensor data.
# Boid Simulation: Simulate "boids" (bird-oid objects) flocking behavior using rules of cohesion, separation, and alignment on arrays of positions and velocities.
# Wave Equation Simulation: Simulate the 1D wave equation using finite differences on a NumPy array.
# Ising Model Simulation: Simulate the 2D Ising model of ferromagnetism using a Monte Carlo method.
# Solving a Maze: Represent a maze as a 2D array and find a path through it.
# Creating a Voronoi Diagram: Given a set of points, create a Voronoi diagram on a 2D grid.
# Diffusion-Limited Aggregation: Simulate the growth of a fractal cluster through diffusion-limited aggregation.
# LU Decomposition: Implement LU decomposition from scratch.
# K-Means Clustering: Implement the K-Means clustering algorithm from scratch.
# Principal Component Analysis (PCA): Implement PCA from scratch using covariance matrices and eigenvectors.
# Ray Tracing (Simple): Render a simple scene with a sphere and a plane using ray tracing on a grid of pixels.
# Density-based clustering (DBSCAN): Implement the core logic of the DBSCAN clustering algorithm.
# Topological Sort: Given a directed acyclic graph represented by an adjacency matrix, perform a topological sort.
# Start typing a prompt

[10 20 30 40]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1  0  0  0]
 [ 0  5  0  0]
 [ 0  0  9  0]
 [ 0  0  0 14]]
[[0.80577253 0.31335832 0.34797645]
 [0.29056579 0.78654662 0.39717193]
 [0.7947823  0.33046585 0.84420984]]
[70 95 72 65 57 68 64 82 78 74]
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]
[1 2 3]
<class 'numpy.ndarray'>
(3, 4) 3 2
int64
8
160
[[2 5]
 [3 6]
 [4 7]]
1 5
[1 2 3] [4 5 6]
[ 5  6  7  8  9 10 11 12 13 14 15]


TypeError: arange() got an unexpected keyword argument 'size'

In [63]:
np.random.randint(1, 101, size=(2, 5))

array([[88, 39, 85, 74, 45],
       [60, 84, 66, 34,  2]])

# Task
Generate, execute, and explain code to demonstrate and answer questions about NumPy array attributes and inspection, including contiguity (C and F order), non-contiguous arrays, strides, base objects, data pointers, array reports, flatten vs ravel (view and copy), and checking for NaN values.

## Generate code

### Subtask:
Generate code to address each of the commented tasks related to array attributes and inspection (tasks 31-40).


**Reasoning**:
The subtask requires generating code to demonstrate various NumPy array attributes and inspection techniques based on the provided comments. I will create a single code block to address each commented task from 31 to 40.



In [3]:
import numpy as np
# Check Contiguity (C-order): Create a standard C-order array and verify its C_CONTIGUOUS flag is True.
c_order_array = np.arange(12).reshape(3, 4)
print(f"C-order array:\n{c_order_array}")
print(f"Is C-contiguous? {c_order_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {c_order_array.flags['F_CONTIGUOUS']}")

# Check Contiguity (F-order): Create a Fortran-order array and verify its F_CONTIGUOUS flag is True.
f_order_array = np.arange(12).reshape(3, 4, order='F')
print(f"\nF-order array:\n{f_order_array}")
print(f"Is C-contiguous? {f_order_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {f_order_array.flags['F_CONTIGUOUS']}")

# Non-Contiguous Array: Create a non-contiguous array by taking a slice with a step (e.g., A[:, ::2]) and check its contiguity flags.
non_contiguous_array = c_order_array[:, ::2]
print(f"\nNon-contiguous array (slice with step):\n{non_contiguous_array}")
print(f"Is C-contiguous? {non_contiguous_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {non_contiguous_array.flags['F_CONTIGUOUS']}")

# Strides: Create a 3x4 array of int32 (4 bytes) and print its strides to understand how memory is traversed.
strides_array = np.arange(12, dtype=np.int32).reshape(3, 4)
print(f"\nArray for strides demonstration:\n{strides_array}")
print(f"Strides: {strides_array.strides}")
print(f"Item size: {strides_array.itemsize}")

# Base Object: Create a view B from an array A (B = A[0:5]). Print B.base to show it refers back to A.
base_array_A = np.arange(10)
base_array_B = base_array_A[0:5]
print(f"\nOriginal array A: {base_array_A}")
print(f"View B: {base_array_B}")
print(f"Base of B: {base_array_B.base}")
print(f"Is B a view of A? {base_array_B.base is base_array_A}")

# Data Pointer: Print the data attribute of an array to see the memory buffer object.
data_pointer_array = np.array([10, 20, 30])
print(f"\nArray for data pointer demonstration: {data_pointer_array}")
print(f"Data pointer: {data_pointer_array.data}")

# Array Report: Write a function that takes an array and prints a full report: its data, shape, strides, dtype, and total memory usage.
def array_report(arr):
    print(f"\n--- Array Report ---")
    print(f"Array Data:\n{arr}")
    print(f"Shape: {arr.shape}")
    print(f"Strides: {arr.strides}")
    print(f"Data Type: {arr.dtype}")
    print(f"Total Memory Usage (bytes): {arr.nbytes}")
    print(f"--------------------")

report_array = np.random.rand(2, 3)
array_report(report_array)

# Flatten vs Ravel (View): Create a C-contiguous array, ravel it, and show that modifying the raveled array changes the original.
c_array_for_ravel = np.arange(6).reshape(2, 3)
raveled_array = c_array_for_ravel.ravel()
print(f"\nOriginal C-contiguous array for ravel:\n{c_array_for_ravel}")
print(f"Raveled array (view): {raveled_array}")
raveled_array[0] = 999
print(f"Original array after modifying raveled view:\n{c_array_for_ravel}")

# Flatten vs Ravel (Copy): Create a C-contiguous array, flatten it, and show that modifying the flattened array does not change the original.
c_array_for_flatten = np.arange(6).reshape(2, 3)
flattened_array = c_array_for_flatten.flatten()
print(f"\nOriginal C-contiguous array for flatten:\n{c_array_for_flatten}")
print(f"Flattened array (copy): {flattened_array}")
flattened_array[0] = 888
print(f"Original array after modifying flattened copy:\n{c_array_for_flatten}")

# Check for NaN: Create an array with a np.nan value and use np.isnan() to get a boolean mask.
nan_array = np.array([1, 2, np.nan, 4, 5])
print(f"\nArray with NaN: {nan_array}")
print(f"Boolean mask for NaN: {np.isnan(nan_array)}")

C-order array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Is C-contiguous? True
Is F-contiguous? False

F-order array:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Is C-contiguous? False
Is F-contiguous? True

Non-contiguous array (slice with step):
[[ 0  2]
 [ 4  6]
 [ 8 10]]
Is C-contiguous? False
Is F-contiguous? False

Array for strides demonstration:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Strides: (16, 4)
Item size: 4

Original array A: [0 1 2 3 4 5 6 7 8 9]
View B: [0 1 2 3 4]
Base of B: [0 1 2 3 4 5 6 7 8 9]
Is B a view of A? True

Array for data pointer demonstration: [10 20 30]
Data pointer: <memory at 0x7d432c0bd6c0>

--- Array Report ---
Array Data:
[[0.37714656 0.12758074 0.84844386]
 [0.43594734 0.89883197 0.11625087]]
Shape: (2, 3)
Strides: (24, 8)
Data Type: float64
Total Memory Usage (bytes): 48
--------------------

Original C-contiguous array for ravel:
[[0 1 2]
 [3 4 5]]
Raveled array (view): [0 1 2 3 4 5]
Original array after modifying raveled view:
[[999

## Execute code

### Subtask:
Execute the generated code to demonstrate and inspect NumPy array attributes.


**Reasoning**:
Execute the generated code block to demonstrate and inspect NumPy array attributes as requested in the subtask.



In [62]:
# Check Contiguity (C-order): Create a standard C-order array and verify its C_CONTIGUOUS flag is True.
c_order_array = np.arange(12).reshape(3, 4)
print(f"C-order array:\n{c_order_array}")
print(f"Is C-contiguous? {c_order_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {c_order_array.flags['F_CONTIGUOUS']}")

# Check Contiguity (F-order): Create a Fortran-order array and verify its F_CONTIGUOUS flag is True.
f_order_array = np.arange(12).reshape(3, 4, order='F')
print(f"\nF-order array:\n{f_order_array}")
print(f"Is C-contiguous? {f_order_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {f_order_array.flags['F_CONTIGUOUS']}")

# Non-Contiguous Array: Create a non-contiguous array by taking a slice with a step (e.g., A[:, ::2]) and check its contiguity flags.
non_contiguous_array = c_order_array[:, ::2]
print(f"\nNon-contiguous array (slice with step):\n{non_contiguous_array}")
print(f"Is C-contiguous? {non_contiguous_array.flags['C_CONTIGUOUS']}")
print(f"Is F-contiguous? {non_contiguous_array.flags['F_CONTIGUOUS']}")

# Strides: Create a 3x4 array of int32 (4 bytes) and print its strides to understand how memory is traversed.
strides_array = np.arange(12, dtype=np.int32).reshape(3, 4)
print(f"\nArray for strides demonstration:\n{strides_array}")
print(f"Strides: {strides_array.strides}")
print(f"Item size: {strides_array.itemsize}")

# Base Object: Create a view B from an array A (B = A[0:5]). Print B.base to show it refers back to A.
base_array_A = np.arange(10)
base_array_B = base_array_A[0:5]
print(f"\nOriginal array A: {base_array_A}")
print(f"View B: {base_array_B}")
print(f"Base of B: {base_array_B.base}")
print(f"Is B a view of A? {base_array_B.base is base_array_A}")

# Data Pointer: Print the data attribute of an array to see the memory buffer object.
data_pointer_array = np.array([10, 20, 30])
print(f"\nArray for data pointer demonstration: {data_pointer_array}")
print(f"Data pointer: {data_pointer_array.data}")

# Array Report: Write a function that takes an array and prints a full report: its data, shape, strides, dtype, and total memory usage.
def array_report(arr):
    print(f"\n--- Array Report ---")
    print(f"Array Data:\n{arr}")
    print(f"Shape: {arr.shape}")
    print(f"Strides: {arr.strides}")
    print(f"Data Type: {arr.dtype}")
    print(f"Total Memory Usage (bytes): {arr.nbytes}")
    print(f"--------------------")

report_array = np.random.rand(2, 3)
array_report(report_array)

# Flatten vs Ravel (View): Create a C-contiguous array, ravel it, and show that modifying the raveled array changes the original.
c_array_for_ravel = np.arange(6).reshape(2, 3)
raveled_array = c_array_for_ravel.ravel()
print(f"\nOriginal C-contiguous array for ravel:\n{c_array_for_ravel}")
print(f"Raveled array (view): {raveled_array}")
raveled_array[0] = 999
print(f"Original array after modifying raveled view:\n{c_array_for_ravel}")

# Flatten vs Ravel (Copy): Create a C-contiguous array, flatten it, and show that modifying the flattened array does not change the original.
c_array_for_flatten = np.arange(6).reshape(2, 3)
flattened_array = c_array_for_flatten.flatten()
print(f"\nOriginal C-contiguous array for flatten:\n{c_array_for_flatten}")
print(f"Flattened array (copy): {flattened_array}")
flattened_array[0] = 888
print(f"Original array after modifying flattened copy:\n{c_array_for_flatten}")

# Check for NaN: Create an array with a np.nan value and use np.isnan() to get a boolean mask.
nan_array = np.array([1, 2, np.nan, 4, 5])
print(f"\nArray with NaN: {nan_array}")
print(f"Boolean mask for NaN: {np.isnan(nan_array)}")

C-order array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Is C-contiguous? True
Is F-contiguous? False

F-order array:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Is C-contiguous? False
Is F-contiguous? True

Non-contiguous array (slice with step):
[[ 0  2]
 [ 4  6]
 [ 8 10]]
Is C-contiguous? False
Is F-contiguous? False

Array for strides demonstration:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Strides: (16, 4)
Item size: 4

Original array A: [0 1 2 3 4 5 6 7 8 9]
View B: [0 1 2 3 4]
Base of B: [0 1 2 3 4 5 6 7 8 9]
Is B a view of A? True

Array for data pointer demonstration: [10 20 30]
Data pointer: <memory at 0x7ed9ffdf37c0>

--- Array Report ---
Array Data:
[[0.78549262 0.96585911 0.36937839]
 [0.81550209 0.69592686 0.24296629]]
Shape: (2, 3)
Strides: (24, 8)
Data Type: float64
Total Memory Usage (bytes): 48
--------------------

Original C-contiguous array for ravel:
[[0 1 2]
 [3 4 5]]
Raveled array (view): [0 1 2 3 4 5]
Original array after modifying raveled view:
[[999

## Explain results

### Subtask:
Explain the output of the code and answer the questions posed in the comments.


## Summary:

### Data Analysis Key Findings

*   A standard C-order NumPy array is C-contiguous but not F-contiguous, while an F-order array is F-contiguous but not C-contiguous.
*   Taking a slice with a step from a contiguous array results in a non-contiguous array.
*   The `strides` attribute indicates the number of bytes to step in each dimension to reach the next element.
*   The `base` attribute of a view refers back to the original array, confirming the view relationship.
*   The `data` attribute provides a memory buffer object for the array's data.
*   `ravel()` creates a view of the original array, so modifying the raveled array changes the original.
*   `flatten()` creates a copy of the original array, so modifying the flattened array does not change the original.
*   `np.isnan()` returns a boolean mask indicating the presence of NaN values in an array.

### Insights or Next Steps

*   Understanding array contiguity and strides is crucial for optimizing performance in NumPy operations, especially when dealing with large arrays or external libraries.
*   Being aware of whether an operation returns a view or a copy (`ravel` vs. `flatten`) is essential to avoid unintended modifications of the original data.
